import os
import time
import shutil
import re
from src.core.state import AgentState
from src.io.base64_encoder import encode_file_to_base64
from src.io.text_enrichment import convert_all_markdown_to_richtext
from src.io.strategy_selector import get_strategy

def sanitize_filename(name: str) -> str:
    """Removes invalid characters to make the firm name safe for the file system."""
    name = str(name).strip()
    # Keep only alphanumeric characters, spaces, hyphens, and underscores
    name = re.sub(r'(?u)[^-\w\s]', '', name)
    # Replace spaces and hyphens with a single underscore
    return re.sub(r'[-\s]+', '_', name)

def assembly_node(state: AgentState) -> dict:
    """
    Assembler Node:
    Takes the complete JSON data, injects it into the template, 
    names it cleanly, and removes any temporary child folders.
    """
    updates = {"current_step": "assembly", "messages": []}

    submission_data = getattr(state, "submission", None)
    if submission_data:
        submission_dict = submission_data.model_dump(exclude_none=True)
    else:
        submission_dict = {}

    # --- 1. Recuperación BLINDADA (Soporta dict y objeto) ---
    if isinstance(state, dict):
        sub_type = state.get("target_submission_type", "Legal500")
        state_config = state.get("config", {})
        metadata = state.get("metadata", {})
    else:
        sub_type = getattr(state, "target_submission_type", "Legal500")
        state_config = getattr(state, "config", {}) or {}
        metadata = getattr(state, "metadata", {}) or {}

    # --- 2. RUTEO DE EMERGENCIA (Si el config se perdió en el camino) ---
    if not state_config:
        if hasattr(metadata, "guide"):
            guide = metadata.guide
        elif isinstance(metadata, dict):
            guide = metadata.get("guide", "")
        else:
            guide = ""
            
        guide = str(guide).lower() if guide else ""
        
        from src.io.strategy_selector import get_config_path
        import yaml
        config_path = get_config_path(sub_type, guide)
        print(f"🔥 DEBUG ASSEMBLER: Rescatando YAML desde -> {config_path}")
        
        try:
            with open(config_path, "r", encoding="utf-8") as f:
                state_config = yaml.safe_load(f) or {}
        except Exception as e:
            print(f"❌ Error leyendo {config_path} en assembler: {e}")

    # 3. Inicializamos la estrategia con el config REPLETO
    strategy = get_strategy(sub_type, state_config)

    # 1. Extract and sanitize the Firm Name for the file
    raw_firm_name = "Unknown_Firm"
    raw_practice_area = "Unknown_Practice"
    
    # --- Check the submission type to pull the data from the correct schema ---
    if sub_type == "Legal500" and "identity" in submission_dict and submission_dict["identity"]:
        raw_firm_name = submission_dict["identity"].get("firm_name", "Unknown_Firm")
        raw_practice_area = submission_dict["identity"].get("practice_area", "Unknown_Practice")
        
    elif sub_type == "Chambers":
        section_a = (
            submission_dict.get("A_preliminary_information") or 
            submission_dict.get("preliminary_information") or 
            {}
        )
        raw_firm_name = section_a.get("A1_firm_name") or "Unknown_Firm"
        raw_practice_area = section_a.get("A2_practice_area") or "Unknown_Practice"
    
    firm_name = sanitize_filename(raw_firm_name)
    practice_area = sanitize_filename(raw_practice_area)
    timestamp = int(time.time())
    
    # Define our perfect final file name
    final_filename = f"{firm_name}_{sub_type}_{practice_area}_{timestamp}.docx"

    # 2. Setup the paths
    base_dir = os.path.join("data", "processed")
    temp_dir = os.path.join(base_dir, f"temp_{timestamp}")
    os.makedirs(temp_dir, exist_ok=True)
    
    final_doc_path = os.path.join(base_dir, final_filename)

    try:
        # Convert markdown generated by the Optimizer into rich text for Word
        convert_all_markdown_to_richtext(submission_dict)

        # ========================================================
        # 🕵️‍♂️ TRAMPA DE DEBUGGING ACTUALIZADA (Chambers & Legal500 Aware)
        # ========================================================
        print("\n" + "="*50)
        print("🕵️‍♂️ DEBUG ASSEMBLER: VERIFICANDO MATTERS OPTIMIZADOS")
        print("="*50)
        
        if sub_type == "Chambers":
            pub_info = submission_dict.get("D_publishable_information", {})
            casos = pub_info.get("publishable_matters", []) if pub_info else []
            
            if casos:
                print(f"✅ Chambers Schema Detectado.")
                print(f"📊 Cantidad de casos listos para exportar: {len(casos)}")
                print(f"📝 Cliente 1: {casos[0].get('D1_name_of_client', 'SIN NOMBRE')}")
                print(f"👨‍⚖️ Lead Partner: {casos[0].get('D5_lead_partner', 'SIN NOMBRE')}")
                
                # Check if ghostwriting was successful
                desc = casos[0].get('D2_summary_of_matter_and_role', '')
                print(f"✍️ Longitud del abstract final: {len(str(desc))} caracteres.")
            else:
                print("⚠️ ALERTA: No hay casos publicables en 'D_publishable_information'.")
                
        elif sub_type == "Legal500":
            if "publishable_matters" in submission_dict:
                casos = submission_dict["publishable_matters"]
                print(f"✅ Legal500 Schema Detectado. {len(casos)} casos listos.")
            else:
                print("⚠️ ALERTA: No 'publishable_matters' found in root dict.")

        print("="*50 + "\n")
        # ========================================================

        # 3. Let the strategy assemble the document inside the temporary directory
        generated_path = strategy.assemble(submission_dict, temp_dir)
        
        # 4. Move it to the base directory and apply our custom name
        shutil.move(generated_path, final_doc_path)
        updates["messages"].append(f"Assembly node: Document successfully assembled at {final_doc_path}.")

        # 5. Encode the cleanly named file
        encoded_file = encode_file_to_base64(final_doc_path)
        if encoded_file:
            updates["output_base64"] = encoded_file
        else:
            updates["messages"].append("Assembly node Error: encode_file_to_base64 returned None.")
            
    except Exception as e:
        import traceback
        traceback.print_exc()
        updates["messages"].append(f"Assembly node Error: Failed to assemble document: {str(e)}")
        
    finally:
        # 6. CLEANUP: Delete the temporary folder
        if os.path.exists(temp_dir):
            shutil.rmtree(temp_dir)

    return updates